name: Deploy main
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r aws-backend.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.ACCESS_KEY }}
        aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
        application_name: beanstalk
        environment_name: beanstalk-env-2
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: aws-backend.zip
        web: node app.js
        