name: Deploy Node + Vault

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Stop Old Container
      run: |
        docker stop backend || true
        docker rm backend || true

    - name: Remove Old Image
      run: |
        docker rmi backend:latest || true

    - name: Build Image
      run: |
        docker build -t backend:latest .

    - name: Run Container with Vault ENV
      run: |
        docker run -d \
          -p 3002:3002 \
          --name backend \
          -e VAULT_ADDR=${{ secrets.VAULT_ADDR }} \
          -e ROLE_ID=${{ secrets.ROLE_ID }} \
          -e SECRET_ID=${{ secrets.SECRET_ID }} \
          backend:latest

    - name: Show Running Containers
      run: docker ps
