name: Deploy Node + Vault

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/ubuntu/aws-backend

          git pull origin main

          docker stop backend || true
          docker rm backend || true
          docker rmi backend:latest || true

          docker build -t backend:latest .

          docker run -d \
            -p 3002:3002 \
            --name backend \
            -e VAULT_ADDR=${{ secrets.VAULT_ADDR }} \
            -e ROLE_ID=${{ secrets.ROLE_ID }} \
            -e SECRET_ID=${{ secrets.SECRET_ID }} \
            backend:latest
